config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'houses#index'

  resources :operations
  resources :houses do
    resources :reservations, only:[:create, :destroy]
    get 'my_houses', to: 'houses#customer_houses', on: :collection
  end

  get 'reservations', to: 'reservations#index'

  resources :user, :controller => "user"
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to('IMOBILIÁRIA', root_path, :class => "navbar-brand") %>
<% if user_signed_in? %>
  <ul class="nav navbar-nav">
    <li><%= link_to('Houses', houses_path) %></li>
    <% if current_user.customer? %>
      <li><%= link_to('My Houses', my_houses_houses_path) %></li>
    <% end %>
    <% if current_user.admin? %>
      <li><%= link_to('Operation', operations_path) %></li>
    <% end %>
    <li><%= link_to('Reserves', reservations_path) %></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        <%= current_user.name %><span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <% if current_user.admin? %>
          <li><%= link_to('New User', new_user_path) %></li>
        <% end %>
        <li><%= link_to('Edit account', edit_user_registration_path) %></li>
        <li><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %></li>
      </ul>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "IMOBILIÁRIA" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar navbar-default">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </div>
  </body>
</html>